<!DOCTYPE html>
<html>
<head>
	<title>Header</title>
	<!-- Bootstrap CSS CDN -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

	<!-- Custom CSS -->
	<link rel="stylesheet" type="text/css" href="css/header.css">
	<link rel="stylesheet" type="text/css" href="css/footer.css">
	<link rel="stylesheet" type="text/css" href="css/home.css">
</head>
<body>
	<!-- ********* HEADER START ********* -->
	<!-- Header Jumbotron -->
	<div class="jumbotron jumbotron-fluid" id="header-jumbotron">
		<div class="container">
			<p id="name">
				Md Tanvirul Islam
			</p>
			<p class="text-muted" id="designation">
				Computer Science and Electrical Engineering<span class="text-seperator"> | </span>UCONN '19
			</p>
		</div>
	</div>

	<!-- Navigation Bar -->
	<navbar class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
		<!-- Collapse Button -->
		<button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
			<!-- Icon -->
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="container">
			<!-- Collapsable div -->
			<div class="collapse navbar-collapse" id="collapse_target">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link active" href="#">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Education</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Résumé</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Research and Projects</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Blog</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Contact</a>
					</li>
				</ul>
			</div>
			
		</div>
	</navbar>
	<!-- ********* HEADER END ********* -->

	<!-- JQUERY CDN -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<!-- Popper CDN -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<!-- JavaScript CDN -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
	<!-- Custom JS -->
	<script type="text/javascript" src="js/home.js"></script>
</body>
</html>


